export const CONTENT_TYPES = ["snippet", "prompt", "command", "note"];
export const LANGUAGE_TYPES = ["snippet", "command"];
export const MARKDOWN_TYPES = ["note", "prompt"];
export const CODE_TYPES = ["snippet", "command"];

export const LANGUAGES = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Rust",
  "Go",
  "Java",
  "C",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Dart",
  "Lua",
  "R",
  "Scala",
  "Elixir",
  "Haskell",
  "Shell",
  "PowerShell",
  "SQL",
  "GraphQL",
  "HTML",
  "CSS",
  "SCSS",
  "JSON",
  "YAML",
  "TOML",
  "XML",
  "Markdown",
  "Dockerfile",
  "Terraform",
  "Prisma",
] as const;
